### ISSUE TITLE
Returns false for cmder although it does handle unicode

### ISSUE THREAD

**Issue by KonradLinkowski** [sindresorhus/is-unicode-supported#4]
The function should probably return true for that particular terminal.
cmder website: https://cmder.net/

**Comment by Richienb** [comment]
Whilst Cmder does indeed support more unicode characters, it is not able to display emojis. Regardless, here's how to check for the terminal: `process.env.ConEmuTask === '{cmd::Cmder}'`.

**Comment by ehmicky** [comment]
PR at #8.
